### ISSUE TITLE
Create Click and Drag Mouse Tracking Framework

### ISSUE THREAD

**Issue by fretws** [info442-spr22/g-team#21]
Prerequisites: Canvas element on the scrapbook page

Implement a way in which we can track the beginning and ending position of the user's mouse when they click and hold on the canvas. 
- [ ] When the user begins holding down their left mouse button anywhere other than the canvas or its children html elements, it should be ignored
- [ ] When the user begins holding down their left mouse button on the canvas or its children, the position of the mouse should be logged to the console, i.e. `console.log(position)`
- [ ] When the user releases their left mouse button, the position of the mouse should also be logged to the console, no matter whether their mouse remains on the canvas or its children

Supports requirements:
```
C.5
C.7.i
C.13.v
E.4 - E.6
```
